# Auto-generated by scripts/sync_schemas.py
# Run this script to validate schema consistency after manual edits.

from ai_layer.rag.models import Chunk, ChunkMetadataModel
from ai_layer.rag.vectorstores.chroma_store import ChromaVectorStore
import inspect

def check():
    # 1. ChunkMetadataModel has required fields
    required = ["source_id", "source_type", "chunk_index", "total_chunks", "rerank_score", "extra"]
    for f in required:
        assert f in ChunkMetadataModel.model_fields, f"Missing field: {f}"

    # 2. Chunk has sys_hash
    assert "sys_hash" in Chunk.model_fields, "Chunk missing sys_hash"

    # 3. ChromaVectorStore.add_chunks accepts sys_hash kwarg
    sig = inspect.signature(ChromaVectorStore.add_chunks)
    assert "sys_hash" in sig.parameters, "add_chunks missing sys_hash kwarg"

    print("Schema integrity check passed.")

if __name__ == "__main__":
    check()
