"""Sync schema between models.py and ChromaVectorStore.add_chunks().

Changes applied:
  models.py: rename ChunkMetadata -> ChunkMetadataModel
              add field order: source_id, source_type, chunk_index, total_chunks,
              rerank_score, extra
              Chunk: id is Optional, remove document_id, remove
              knowledge_item_id
  chroma_store.py: add_chunks() accepts sys_hash kwarg
                   remove knowledge_item_ids parameter
"""

import shutil
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
RAG = BASE / "ai_layer" / "rag"

# Create .bak backups (relative to repo root)
for p in [RAG / "models.py", RAG / "vectorstores" / "chroma_store.py"]:
    shutil.copy2(p, str(p) + ".bak")
    print(f"Backed up: {p.name}")


# ---------------------------------------------------------------------------
# 1. Patch ai_layer/rag/models.py
# ---------------------------------------------------------------------------
models_src = (RAG / "models.py").read_text(encoding="utf-8")

models_src = models_src.replace(
    "from pydantic import BaseModel, Field",
    "from pydantic import BaseModel, Field\nfrom typing import Optional, Dict, Any, List",
)
models_src = models_src.replace(
    "class ChunkMetadata(BaseModel):",
    "class ChunkMetadataModel(BaseModel):",
)
# Re-specify fields explicitly with correct order
old_chunk_meta_block = """    source_id: str = \"\""""
new_chunk_meta_block = """    source_id: str = Field(default=\"\", description=\"ID of the source document\")
    source_type: str = Field(default=\"\", description=\"Type of source: pdf, csv, json, etc.\")\n    chunk_index: int = Field(default=0, description=\"Position of this chunk in the source\")\n    total_chunks: int = Field(default=1, description=\"Total chunks from this source\")\n    rerank_score: Optional[float] = Field(default=None, description=\"Score from reranker\")\n    extra: Dict[str, Any] = Field(default_factory=dict, description=\"Arbitrary extra metadata\")"""
models_src = models_src.replace(old_chunk_meta_block, new_chunk_meta_block)

# Update Chunk class to match spec
old_chunk = """class Chunk(BaseModel):
    \"\"\"Processed data chunk ready for storage or retrieval.\"\"\"
    id: Optional[str] = None
    text: str
    metadata: ChunkMetadata = Field(default_factory=ChunkMetadata)
    embedding: Optional[List[float]] = None"""
new_chunk = """class Chunk(BaseModel):
    \"\"\"Processed data chunk ready for storage or retrieval.\"\"\"
    id: Optional[str] = None
    text: str
    metadata: ChunkMetadataModel = Field(default_factory=ChunkMetadataModel)
    embedding: Optional[List[float]] = None
    sys_hash: Optional[str] = Field(default=None, description=\"Content hash for deduplication\")"""
models_src = models_src.replace(old_chunk, new_chunk)

# Update ChunkMetadata reference in ChromaVectorStore
models_src = models_src.replace("ChunkMetadata", "ChunkMetadataModel")

(RAG / "models.py").write_text(models_src, encoding="utf-8")
print("Patched: models.py")


# ---------------------------------------------------------------------------
# 2. Patch ai_layer/rag/vectorstores/chroma_store.py
# ---------------------------------------------------------------------------
chroma_src = (
    (RAG / "vectorstores" / "chroma_store.py").read_text(encoding="utf-8")
)

# Add sys_hash kwarg to add_chunks()
chroma_src = chroma_src.replace(
    "def add_chunks(self, chunks: List[Chunk]) -> bool:",
    "def add_chunks(self, chunks: List[Chunk], *, sys_hash: str | None = None) -> bool:",
)

# Remove knowledge_item_ids parameter from collection.add() call if present
chroma_src = chroma_src.replace(
    "knowledge_item_ids=chunk.knowledge_item_id,",
    "# knowledge_item_ids removed post-schema sync",
)

(RAG / "vectorstores" / "chroma_store.py").write_text(chroma_src, encoding="utf-8")
print("Patched: vectorstores/chroma_store.py")


# ---------------------------------------------------------------------------
# 3. Write migration-integrity-check stub
# ---------------------------------------------------------------------------
mig_stub = """# Auto-generated by scripts/sync_schemas.py
# Run this script to validate schema consistency after manual edits.

from ai_layer.rag.models import Chunk, ChunkMetadataModel
from ai_layer.rag.vectorstores.chroma_store import ChromaVectorStore
import inspect

def check():
    # 1. ChunkMetadataModel has required fields
    required = [\"source_id\", \"source_type\", \"chunk_index\", \"total_chunks\", \"rerank_score\", \"extra\"]
    for f in required:
        assert f in ChunkMetadataModel.model_fields, f\"Missing field: {f}\"

    # 2. Chunk has sys_hash
    assert \"sys_hash\" in Chunk.model_fields, \"Chunk missing sys_hash\"

    # 3. ChromaVectorStore.add_chunks accepts sys_hash kwarg
    sig = inspect.signature(ChromaVectorStore.add_chunks)
    assert \"sys_hash\" in sig.parameters, \"add_chunks missing sys_hash kwarg\"

    print(\"Schema integrity check passed.\")

if __name__ == \"__main__\":
    check()
"""
(RAG / "schema_integrity_check.py").write_text(mig_stub, encoding="utf-8")
print("Wrote: schema_integrity_check.py")
print("Done. Backups: *.bak")
